### ISSUE TITLE
彬哥你好

### ISSUE THREAD

**Issue by 13120241790** [Sbingo/WanAndroid-MVVM#3]
wan_andorid  mvvm jectpack 项目的作者彬哥你好 ，目前研究您的开源项目时候卡在一个问题上了，卡了很久。能有偿指导一下吗。刚刚从 mvp + Java 转过来的 不胜感激

大概情况是
```
override fun onLoadAfter(params: LoadParams<Int>, callback: LoadCallback<Article>) {
        httpManager.pagingApi.getArticles(pageNo).
                asyncSubscribe({
                    pageNo = it.data?.curPage!!
                    loadMoreSuccess()
                    callback.onResult(it.data?.datas!!)
                },{
                    loadMoreFailed(it.message, params, callback)
                })
    }

```
Debud 时网络请求数据回来了 但是界面没刷新 callback.onResult 回调数据 但是不知道回调到哪里了 
pagedList.observe 的 onchange 方法第一次走了 it 是 0 后续再没有走过

**Comment by binaryshao** [comment]
你好，数据回到了View层的以下代码中：
pagedList.observe(viewLifecycleOwner, Observer {
                adapter.submitList(it)
            })
你说的情况没碰到过，需要具体分析一下

**Comment by 13120241790** [comment]
会不会是先走了 onchanged 方法 这个时候数据 datasource 异步还没回来 导致页面没展示 

@binaryshao 感谢您的回复 能添加一下您的 企鹅 或者 wechat 吗 ，这里评论及时性太差好像想把一个事情描述清楚不是那么简单  当然在您有时间的前提下，否则不会打扰您

**Comment by 13120241790** [comment]
@binaryshao 自己已经解决了  还是很感谢你 👍
